<?xml version="1.0" ?>
<point_set_file>
	<file_version>0.1</file_version>
	<point_set>
		<time_series>
			<time_series_id>0</time_series_id>
			<point>
				<id>0</id>
				<specification>0</specification>
				<x>80.0</x>
				<y>74.0</y>
				<z>74.0</z>
			</point>
			<point>
				<id>1</id>
				<specification>0</specification>
				<x>109.0</x>
				<y>111.0</y>
				<z>87.0</z>
			</point>
		</time_series>
	</point_set>
</point_set_file>
